export enum IpcChannel {
  BulkwhoisLookup = 'bulkwhois:lookup',
  BulkwhoisLookupPause = 'bulkwhois:lookup.pause',
  BulkwhoisLookupContinue = 'bulkwhois:lookup.continue',
  BulkwhoisLookupStop = 'bulkwhois:lookup.stop',
  BulkwhoisInputFile = 'bulkwhois:input.file',
  BulkwhoisInputWordlist = 'bulkwhois:input.wordlist',
  BwaInputFile = 'bwa:input.file',
  BwaAnalyserStart = 'bwa:analyser.start',
  ToInputFile = 'to:input.file',
  ToProcess = 'to:process',
  SingleWhoisLookup = 'singlewhois:lookup',
  ParseCsv = 'csv:parse',
  AvailabilityCheck = 'availability:check',
  DomainParameters = 'availability:params',
  OpenPath = 'shell:openPath',
  OpenDataDir = 'app:open-data-dir',
  PathJoin = 'path:join',
  PathBasename = 'path:basename',
  GetBaseDir = 'app:get-base-dir'
}
