version: '3'
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/usr/src/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    command: npm start
