name: Node.js CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  pull_request_target:
    branches: ['**']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Check formatting
        run: npm run format -- --check
      - run: npm run lint

  type-check:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - run: npx tsc --noEmit

  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    needs: type-check
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [20.x, 22.x, 24.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - run: npm test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.node-version }}
          path: coverage/

  merge-coverage:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          path: coverage-files
          merge-multiple: true
      - name: Merge coverage
        run: |
          npx istanbul-merge coverage-files/**/coverage-final.json > coverage-final.json
          mkdir -p .nyc_output
          cp coverage-final.json .nyc_output/out.json
      - name: Check coverage
        run: npx nyc check-coverage --lines=70
      - uses: actions/upload-artifact@v4
        with:
          name: merged-coverage
          path: coverage-final.json

  e2e:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Cache Electron
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-electron-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run e2e tests
        run: xvfb-run -a npm run test:e2e

  package:
    needs: e2e
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Cache Electron
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-electron-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - run: npm run package-linux
      - run: mv release_builds release_builds-${{ matrix.node-version }}
      - uses: actions/upload-artifact@v4
        with:
          name: linux-package-${{ matrix.node-version }}
          path: release_builds-${{ matrix.node-version }}

  package-windows:
    needs: e2e
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Cache Electron
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-electron-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - run: npm run package-win
      - run: mv release_builds release_builds-${{ matrix.node-version }}
      - uses: actions/upload-artifact@v4
        with:
          name: windows-package-${{ matrix.node-version }}
          path: release_builds-${{ matrix.node-version }}

  package-macos:
    needs: e2e
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: macos-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Cache Electron
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-electron-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - run: npm run package-mac
      - run: mv release_builds release_builds-${{ matrix.node-version }}
      - uses: actions/upload-artifact@v4
        with:
          name: macos-package-${{ matrix.node-version }}
          path: release_builds-${{ matrix.node-version }}
